FROM neo4j:3.1.2

LABEL Description="Neo4j (community) docker image" \
      BaseImageOS="apline" \ 
      ImageBuildNumber="1" \ 
      BaseImageVersion="3.1.2" \
  	   BaseImageName="neo4j" \
      LogCollectionMethod="logfiles"
	  
	  
