version: '2'
services:
   nginx:
     image: test/nginx
     volumes:
       - /c/Users/AG/docker-images/log/nginx:/var/log/nginx 
       - /c/Users/AG/docker-images/html:/usr/share/nginx/html:ro     
     ports:
       - "8000:80"

   fluentd:
     image: test/fluentd
     volumes:
       - /c/Users/AG/docker-images/log:/var/log
     depends_on: 
        - es
 
   es:
     image: elasticsearch
     container_name: es_local
     ports:
       - "9200:9200"
   kibana:
     image: kibana
    
     depends_on: 
        - es
     environment:
        ELASTICSEARCH_URL: http://es_local:9200 
     ports:
       - "5601:5601"
    