FROM kibana:5.1.1

LABEL Description="Kibana docker image" \
      BaseImageOS="debian:jessie" \ 
      ImageBuildNumber="1" \ 
      BaseImageVersion="5.1.1" \
	  BaseImageName="kibana" \
	  LogCollectionMethod="none"

