FROM elasticsearch:5.1.1

LABEL Description="ElasticSearch docker image" \
      BaseImageOS="debian:jessie" \ 
      ImageBuildNumber="2" \ 
      BaseImageVersion="5.1.1" \
  	   BaseImageName="elasticsearch" \
      LogCollectionMethod="logfiles"
	  
	  
# Set LOGS_PATH environment variable for log collecting.
ENV LOGS_PATH=/usr/share/elasticsearch/logs

