FROM node:7.7

LABEL Description="NodeJs docker image" \
      BaseImageOS="debian:jessie" \ 
      ImageBuildNumber="1" \ 
      BaseImageVersion="7.76" \
	   BaseImageName="node" \
	  LogCollectionMethod="stdout"

